### PR TITLE
labextension: update to JupyterLab 2.x

### PR DESCRIPTION
**Pull request by StefanoFioravanzo**
A list of required changes can be found here:
https://jupyterlab.readthedocs.io/en/latest/developer/extension_migration.html

Signed-off-by: Stefano Fioravanzo <stefano@arrikto.com>
Signed-off-by: DavidSpek <vanderspek.david@gmail.com>

### CODE REVIEW

**Comment by StefanoFioravanzo** [comment]
Ref to draft PR #153 by @DavidSpek

**Comment by DavidSpek** [comment]
Awesome, I see you got the part in NotebookUtils.tsx fixed at line 321 that I had gotten stuck on and didn't have time to revisit yet. I was actually just now about to start looking at kale using a legacy jupyterlab image, but I guess I will test with this version in jupyterlab 2.1.4.

**Comment by DavidSpek** [comment]
I seem to be running into an error when trying to install the extension in my existing notebook image. After launching the notebook I get the message:
```
@jupyter-widgets/jupyterlab-manager needs to be included in build
@bokeh/jupyter_bokeh needs to be included in build
jupyter-matplotlib needs to be included in build
```
The build performs successfully and the page is refreshed. 

I then `cd` go into the labexntension folder I added from this pull request and execute `jupyter labextension install` which completes successfully and I reload the page. Next, a window pops up with the following error message:
```
An unexpected error has occurred
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

Type: JS

Message: TypeError: Cannot convert undefined or null to object

Details: Please see the console for more information
```
In the browser developer tools the following error shows:
```
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at WidgetManager._loadFromKernel (manager.js:166)
    at async WidgetManager.restoreWidgets (manager.js:136)
_loadFromKernel @ manager.js:166
async function (async)
restoreWidgets @ manager.js:136
WidgetManager @ manager.js:77
registerWidgetManager @ plugin.js:65
(anonymous) @ plugin.js:143
invokeSlot @ index.es6.js:459
emit @ index.es6.js:416
push.JGtG.Signal.emit @ index.es6.js:99
(anonymous) @ widgettracker.js:38
invokeSlot @ index.es6.js:459
emit @ index.es6.js:416
push.JGtG.Signal.emit @ index.es6.js:99
add @ restorablepool.js:131
async function (async)
add @ restorablepool.js:127
add @ widgettracker.js:114
add @ tracker.js:47
(anonymous) @ index.js:396
invokeSlot @ index.es6.js:459
emit @ index.es6.js:416
push.JGtG.Signal.emit @ index.es6.js:99
createNew @ default.js:349
createWidget @ widgetmanager.js:60
_createOrOpenDocument @ manager.js:456
open @ manager.js:274
openOrReveal @ manager.js:298
(anonymous) @ index.js:315
Promise.then (async)
execute @ index.js:315
push.AB7C.CommandRegistry.execute @ index.es6.js:357
(anonymous) @ restorablepool.js:236
restore @ restorablepool.js:228
async function (async)
restore @ restorablepool.js:227
restore @ widgettracker.js:203
restore @ layoutrestorer.js:182
activateNotebookHandler @ index.js:359
(anonymous) @ index.es6.js:162
Promise.then (async)
push.8h0S.Application.activatePlugin @ index.es6.js:161
push.8h0S.Application.resolveRequiredService @ index.es6.js:205
(anonymous) @ index.es6.js:155
push.8h0S.Application.activatePlugin @ index.es6.js:155
push.8h0S.Application.resolveRequiredService @ index.es6.js:205
(anonymous) @ index.es6.js:155
push.8h0S.Application.activatePlugin @ index.es6.js:155
(anonymous) @ index.es6.js:281
push.8h0S.Application.start @ index.es6.js:280
main @ index.out.js:1083
load (async)
ANye @ index.out.js:1129
__webpack_require__ @ bootstrap:83
0 @ bootstrap:221
__webpack_require__ @ bootstrap:83
checkDeferredModules @ bootstrap:44
webpackJsonpCallback @ bootstrap:31
(anonymous) @ vendors~main.c9f62d01c9063e71103e.js:1
```

It is very possible that this is caused by my notebook image and not by the changes in this pull request, as I was able to run the kubeflow-kale plugin without an issue locally. I am currently running it on an on-perm kubernetes cluster deployed using kfctl_istio_dex.v1.0.2. The notebook image does contain 2 different python kernels, with 3.7 being the default for compatibility with the ml_metadata requirement for kubeflow-kale. 

For reference I have attached the Dockerfile, and it can be found at davidspek/kubeflow-datascience-notebook:0.8.6. 
[Dockerfile.txt](https://github.com/kubeflow-kale/kale/files/4905147/Dockerfile.txt)

**Comment by StefanoFioravanzo** [comment]
Hey @DavidSpek we merged this because we tested in several dockerfiles with not issues - @elikatsis did a good review of the PR and actually fixed a few things that were not yet covered. Can you verify if the issue with your Dockerfile still persists? 

If so, please open a specific issue so that we can tackle it!

**Pull request merged**
