### PR TITLE
Initial changes for jupyterlab 2.x support

### PR DESCRIPTION
**Pull request by DavidSpek**
I am busy with setting up kubeflow with some custom jupyter notebook images that I want to add kale to, but the images are running jupyterlab 2.1.5. This is my (failed) attempt at adding support for jupyterlab 2.1.5 (I imagine all versions 2.x as well). I am not a software developer so it is very possible that I have broken things with my edits. Hopefully some of the more skilled developers can use this as a base to properly start supporting jupyterlab 2.x. I systematically made edits to remove the build errors I was experiencing. However, there are still a few pesky build errors I have not been able to figure out which are listed below. 

Remaning build errors:

src/lib/NotebookUtils.tsx:321:67 - error TS2339: Property 'IKernelConnection' does not exist on type 'typeof import("/home/david/kale/labextension/node_modules/@jupyterlab/services/lib/kernel/kernel")'.

321     let options: Kernel.IKernelConnection.IOptions = await Kernel.IKernelConnection.spec.then(kernelSpecs => {
                                                                      ~~~~~~~~~~~~~~~~~

src/lib/NotebookUtils.tsx:321:95 - error TS7006: Parameter 'kernelSpecs' implicitly has an 'any' type.

321     let options: Kernel.IKernelConnection.IOptions = await Kernel.IKernelConnection.spec.then(kernelSpecs => {
                                                                                                  ~~~~~~~~~~~

src/lib/NotebookUtils.tsx:327:25 - error TS2339: Property 'IManager' does not exist on type 'typeof import("/home/david/kale/labextension/node_modules/@jupyterlab/services/lib/kernel/kernel")'.

327     return await Kernel.IManager.startNew(options).then(_kernel => {
                            ~~~~~~~~

src/lib/NotebookUtils.tsx:327:57 - error TS7006: Parameter '_kernel' implicitly has an 'any' type.

327     return await Kernel.IManager.startNew(options).then(_kernel => {
                                                            ~~~~~~~

src/lib/NotebookUtils.tsx:450:36 - error TS2339: Property 'kernel' does not exist on type 'ISessionContext'.

450       notebookPanel.sessionContext.kernel,

### CODE REVIEW

**Comment by StefanoFioravanzo** [comment]
@DavidSpek Thank you for starting this. As a matter of fact, I was looking into this exactly today :) 

You seem to be almost there, let me take a look and suggest how to fix your current errors

**Comment by StefanoFioravanzo** [comment]
@DavidSpek check out https://github.com/kubeflow-kale/kale/pull/155  I have just tried to build locally and have not run experiments yet, but it looks like it's working

**Comment by StefanoFioravanzo** [comment]
And sorry for moving this to another PR but you opened this when I was almost done myself with this :)

**Comment by StefanoFioravanzo** [comment]
@DavidSpek since we both contributed to this work (some of your changes were really useful to complete what I had already started) I'd love for you to be part of PR #155. I added you in the Sign-offs of the commit, please take a look and let me know if it's correct!

It's funny that I started working on this a few hours before you submitted your PR :)
And thank you for opening this draft, we love getting contributions from the community!

**Comment by DavidSpek** [comment]
@StefanoFioravanzo Great work on the new Pull Request. I looked through the code and it seems to all be correct going from my memory. Is there something I need to do to sign-off on the commit?

**Comment by StefanoFioravanzo** [comment]
@DavidSpek Just make sure that I got your name and email right in the commit message and we should be good!

**Comment by DavidSpek** [comment]
@StefanoFioravanzo Looks good to me. If it is common practice to use your full name rather than username on github it would be `David van der Spek`.

**Comment by StefanoFioravanzo** [comment]
@DavidSpek The Sign-off name will be the full name that you provided to git with `git config --global user.name "Name Surname"`. I just used the same name that figures as author in your commits, but if you want to change that to your full name just let me know. You can try this by creating a commit with the `--signoff` flag.

**Comment by StefanoFioravanzo** [comment]
Superseded by #155

**Pull request closed without merging**
